#!/bin/bash

echo "🔍 Getting Vault LoadBalancer URL from Terraform Cloud..."
echo ""
echo "Since kubectl access is not available locally, here's how to get the Vault URL:"
echo ""
echo "📋 MANUAL STEPS:"
echo "1. Go to your Terraform Cloud workspace: tf-aws-dev-eks-vault"
echo "2. Look at the 'Outputs' tab after the last successful apply"
echo "3. Find outputs related to Vault services"
echo ""
echo "🤖 AUTOMATIC METHOD (if you have Terraform CLI configured):"
echo "terraform output -raw vault_public_access_instructions"
echo ""
echo "🔧 OR, if you have kubectl access working elsewhere:"
echo "kubectl get svc -n vault vault-minimal -o wide"
echo "kubectl get svc -n vault vault-minimal -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'"
echo ""
echo "⚡ QUICK CHECK:"
echo "Has the LoadBalancer configuration been applied in Terraform Cloud?"
echo "If not, run 'terraform apply' in the tf-aws-dev-eks-vault workspace first."
echo ""
echo "💡 EXPECTED RESULT:"
echo "You should get a URL like: http://abc123-1234567890.ap-southeast-2.elb.amazonaws.com:8200"
echo "Login with token: myroot"
